universe = docker
docker_image = sdabbasi/indic-lan   
executable = train_base.sh
arguments = $(script)
output = train_base.$(ClusterId).$(ProcId).out
error = train_base.$(ClusterId).$(ProcId).err
log = train_base.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 16
request_memory = 32G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue script from (
  train_model 
)
