run_name: task2_bert_spectral_only
output_dir: ./outputs
save_dir: ./models
seed: 42

data:
  dataset_id: badrex/nnti-dataset-full
  train_split: train
  eval_split: validation
  audio_column: audio_filepath
  label_column: language
  speaker_column: speaker_id
  sampling_rate: 16000
  max_duration_seconds: 7.0
  preprocessing_batch_size: 16
  preprocessing_keep_in_memory: true
  preprocessing_load_from_cache_file: false
  preprocessing_writer_batch_size: 16

model:
  id: facebook/w2v-bert-2.0
  apply_dropout: false
  dropout: 0
  freeze_feature_encoder: false

training:
  batch_size: 8
  eval_batch_size: 8
  gradient_accumulation_steps: 2
  num_train_epochs: 8
  learning_rate: 2.0e-5
  warmup_ratio: 0.1
  weight_decay: 0.01
  lr_scheduler_type: linear
  eval_strategy: steps
  eval_steps: 100
  save_strategy: steps
  save_steps: 100
  logging_steps: 10
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: accuracy
  greater_is_better: true
  fp16: true
  bf16: false
  gradient_checkpointing: true
  dataloader_num_workers: 4
  push_to_hub: false
  group_by_length: false

augmentation:
  enabled: true
  train_only: true
  apply_prob: 1.0

  pitch:
    enabled: false

  spectral:
    enabled: true
    prob: 0.7
    notches_min: 2
    notches_max: 4
    center_freq_min: 200.0
    center_freq_max: 4500.0
    q_min: 0.7
    q_max: 2.5
    attenuation_db_min: -20.0
    attenuation_db_max: -8.0
    highpass_prob: 0.4
    highpass_min_hz: 80.0
    highpass_max_hz: 300.0
    lowpass_prob: 0.4
    lowpass_min_hz: 2500.0
    lowpass_max_hz: 6500.0

  timbre_mask:
    enabled: false

tracking:
  use_wandb: true
  wandb_project: huggingface
  wandb_run_name: task2_bert_spectral_only
  hf_token_env: HF_TOKEN
  wandb_api_key_env: WANDB_API_KEY